spring.application.name=conceptbridge
spring.datasource.url=jdbc:mysql://localhost:3306/concept?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
# PDF Storage
pdf.storage.path=uploads/pdfs

# Create uploads directory automatically
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
